#function read_icytable
#Input: filetoread: full path and file name of xls fil as generated by ICY from ROI export.
#OUtput: Table read with some x y position converted to numbers
read_icytable<-function(filetoread){
	library("xlsx")
	readdata<-read.xlsx(filetoread, 1, header=TRUE,stringsAsFactors=FALSE)
	
	readdata$Center.X<-as.numeric(readdata$Center.X)
	readdata$Center.Y<-as.numeric(readdata$Center.Y)

	return(readdata)
}